mandatoryAccounts:
  - name: Management
    description: AWS Organizations management account
    email: Karthik.Shekar@Ethan.com.au
    organizationalUnit: Root

  - name: LogArchive
    description: Central log archive account
    email: Karthik.Shekar+log@Ethan.com.au
    organizationalUnit: Security

  - name: Audit
    description: Security / audit account
    email: Karthik.Shekar+audit@Ethan.com.au
    organizationalUnit: Security

workloadAccounts: []
